# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addEditCoffeeForm(object):
    def setupUi(self, addEditCoffeeForm):
        addEditCoffeeForm.setObjectName("addEditCoffeeForm")
        addEditCoffeeForm.resize(600, 400)
        addEditCoffeeForm.setMinimumSize(QtCore.QSize(600, 400))
        addEditCoffeeForm.setMaximumSize(QtCore.QSize(600, 400))
        self.label = QtWidgets.QLabel(addEditCoffeeForm)
        self.label.setGeometry(QtCore.QRect(10, 10, 31, 16))
        self.label.setObjectName("label")
        self.spinBox = QtWidgets.QSpinBox(addEditCoffeeForm)
        self.spinBox.setGeometry(QtCore.QRect(30, 10, 561, 21))
        self.spinBox.setObjectName("spinBox")
        self.pushButton = QtWidgets.QPushButton(addEditCoffeeForm)
        self.pushButton.setGeometry(QtCore.QRect(30, 40, 561, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(addEditCoffeeForm)
        self.pushButton_2.setGeometry(QtCore.QRect(30, 80, 561, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.tableWidget = QtWidgets.QTableWidget(addEditCoffeeForm)
        self.tableWidget.setGeometry(QtCore.QRect(30, 120, 561, 261))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)

        self.retranslateUi(addEditCoffeeForm)
        QtCore.QMetaObject.connectSlotsByName(addEditCoffeeForm)

    def retranslateUi(self, addEditCoffeeForm):
        _translate = QtCore.QCoreApplication.translate
        addEditCoffeeForm.setWindowTitle(_translate("addEditCoffeeForm", "add/change data"))
        self.label.setText(_translate("addEditCoffeeForm", "ID:"))
        self.pushButton.setText(_translate("addEditCoffeeForm", "Загрузить"))
        self.pushButton_2.setText(_translate("addEditCoffeeForm", "Сохранить"))
