# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_espresso(object):
    def setupUi(self, espresso):
        espresso.setObjectName("espresso")
        espresso.resize(600, 450)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(espresso.sizePolicy().hasHeightForWidth())
        espresso.setSizePolicy(sizePolicy)
        espresso.setMinimumSize(QtCore.QSize(600, 450))
        espresso.setMaximumSize(QtCore.QSize(600, 450))
        self.textEdit = QtWidgets.QPlainTextEdit(espresso)
        self.textEdit.setGeometry(QtCore.QRect(10, 30, 451, 121))
        self.textEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.textEdit.setObjectName("textEdit")
        self.pushButton = QtWidgets.QPushButton(espresso)
        self.pushButton.setGeometry(QtCore.QRect(480, 70, 101, 41))
        self.pushButton.setObjectName("pushButton")
        self.question = QtWidgets.QLabel(espresso)
        self.question.setGeometry(QtCore.QRect(10, 10, 47, 13))
        self.question.setObjectName("question")
        self.answer = QtWidgets.QLabel(espresso)
        self.answer.setGeometry(QtCore.QRect(10, 160, 47, 13))
        self.answer.setObjectName("answer")
        self.tableWidget = QtWidgets.QTableWidget(espresso)
        self.tableWidget.setGeometry(QtCore.QRect(10, 180, 581, 191))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.addEditBt = QtWidgets.QPushButton(espresso)
        self.addEditBt.setGeometry(QtCore.QRect(10, 390, 181, 51))
        self.addEditBt.setObjectName("addEditBt")

        self.retranslateUi(espresso)
        QtCore.QMetaObject.connectSlotsByName(espresso)

    def retranslateUi(self, espresso):
        _translate = QtCore.QCoreApplication.translate
        espresso.setWindowTitle(_translate("espresso", "espresso"))
        self.pushButton.setText(_translate("espresso", "Запуск"))
        self.question.setText(_translate("espresso", "Запрос:"))
        self.answer.setText(_translate("espresso", "Ответ:"))
        self.addEditBt.setText(_translate("espresso", "Изменить/добавить данные"))
